# Generated by Django 3.2.8 on 2021-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(default='Details...'),
        ),
    ]
