# Generated by Django 3.2.8 on 2021-10-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_postition_column_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='kanban_app.Item'),
        ),
        migrations.AlterField(
            model_name='project',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='columns', to='kanban_app.Column'),
        ),
    ]
