# Generated by Django 3.2.8 on 2021-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_auto_20211013_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.BooleanField(default=True),
        ),
    ]
